(* This module was generated automatically by code in Makefile.cil and machdep.c *)
type mach = {
  version_major: int;     (* Major version number *)
  version_minor: int;     (* Minor version number *)
  version: string;        (* version number *)
  underscore_name: bool;  (* If assembly names have leading underscore *)
  sizeof_short: int;      (* Size of "short" *)
  sizeof_int: int;        (* Size of "int" *)
  sizeof_long: int ;      (* Size of "long" *)
  sizeof_longlong: int;   (* Size of "long long" *)
  sizeof_ptr: int;        (* Size of pointers *)
  sizeof_enum: int;       (* Size of enum types *)
  sizeof_longdouble: int; (* Size of "long double" *)
  sizeof_sizeof: int;     (* Size of "sizeof(T)" *)
  sizeof_wchar: int;      (* Size of "wchar_t" *)
  sizeof_void: int;       (* Size of "void" *)
  sizeof_fun: int;        (* Size of function *)
  alignof_longlong: int;  (* Alignment of "long long" *)
  alignof_double: int;    (* Alignment of "double" *)
  alignof_longdouble: int;  (* Alignment of "long double" *)
  alignof_str: int;       (* Alignment of strings *)
  alignof_fun: int;       (* Alignment of function *)
  char_is_unsigned: bool; (* Whether "char" is unsigned *)
  const_string_literals: bool; (* Whether string literals have const chars *)
  little_endian: bool; (* whether the machine is little endian *)
}
let gcc = {
(* Generated by code in src/machdep.c *)
	 version_major    = 3;
	 version_minor    = 3;
	 version          = "3.3.3 (SuSE Linux)";
	 sizeof_int       = 4;
	 sizeof_short     = 2;
	 sizeof_long      = 8;
	 sizeof_longlong  = 8;
	 sizeof_ptr       = 8;
	 sizeof_enum      = 4;
	 sizeof_longdouble  = 16;
	 sizeof_wchar     = 4;
	 sizeof_sizeof    = 8;
	 sizeof_void      = 1;
	 sizeof_fun       = 1;
	 alignof_longlong = 8;
	 alignof_double = 8;
	 alignof_longdouble = 16;
	 alignof_str = 1;
	 alignof_fun = 1;
	 char_is_unsigned = false;
	 const_string_literals = true;
	 little_endian = true;
	 underscore_name = false ;
}
let hasMSVC = false
let msvc = {
(* Generated by code in src/machdep.c *)
	 version_major    = 3;
	 version_minor    = 3;
	 version          = "3.3.3 (SuSE Linux)";
	 sizeof_int       = 4;
	 sizeof_short     = 2;
	 sizeof_long      = 8;
	 sizeof_longlong  = 8;
	 sizeof_ptr       = 8;
	 sizeof_enum      = 4;
	 sizeof_longdouble  = 16;
	 sizeof_wchar     = 4;
	 sizeof_sizeof    = 8;
	 sizeof_void      = 1;
	 sizeof_fun       = 1;
	 alignof_longlong = 8;
	 alignof_double = 8;
	 alignof_longdouble = 16;
	 alignof_str = 1;
	 alignof_fun = 1;
	 char_is_unsigned = false;
	 const_string_literals = true;
	 little_endian = true;
	 underscore_name = true ;
}
let gccHas__builtin_va_list = true
let __thread_is_keyword = true
